os: linux
dist: focal
language: c

compiler:
 - gcc

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - cppcheck

#
# install:
#  - sudo apt-get update
#  - sudo apt-get install --yes libgtest-dev

# - sudo apt-get install --yes gcovr

before_script:
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
#  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake .
  - make

#
# jobs:
# - stage: Build
#   script:
#    - cd /usr/src/gtest
#    - sudo cmake CMakeLists.txt
#    - sudo make
#    - sudo cp *.a /usr/lib
#    - cd "${TRAVIS_BUILD_DIR}"
#    - cmake .
#    - make


  #  - sudo mkdir build
  #  - cd build
  #  - sudo cmake .. 
  #  - sudo make



 # - stage: Test
script:
  #- cppcheck --enable=all main
  - cppcheck project/src/* --error-exitcode=1
  - cppcheck project/include/* --error-exitcode=1
  - cppcheck project/tests/* --error-exitcode=1
  - ./${TRAVIS_BUILD_DIR}/stress_test # change 1
  - cd "${TRAVIS_BUILD_DIR}" #change 1



  # - stage: Coverage
  #   script:
  #     - bash <(curl -s https://codecov.io/bash)

  # - stage: TestCoverage
  #   script:
  #    - cmake -B build -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=1
  #    - make -C build all test
  #    - curl -Os https://uploader.codecov.io/latest/linux.codecov
  #    - chmod +x codecov
  #    - ./codecov -f <(gcovr -x)
  # - stage: Sanitize
  #   script:
  #    - cmake -B build -DCMAKE_BUILD_TYPE=Debug -DWITH_SANITIZERS=1
  #    - make -C build
  #    - cd build && ctest -- output-on-failure