os: linux
dist: focal
language: c

compiler:
 - gcc

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - cppcheck
      - astyle


before_script:
  - astyle -n -r project/*.h
  - astyle -n -r project/*.c
  - astyle -n -r project/*.cpp
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake .
  - make

 
script:
  - valgrind --track-origins=yes --leak-check=full ./matrix_test_consistent
  - valgrind --track-origins=yes --leak-check=full ./matrix_test_parallel
  - valgrind --track-origins=yes --leak-check=full ./stress_gtest
  - cppcheck project/src/* --error-exitcode=1
  - cppcheck project/include/* --error-exitcode=1
  - cppcheck project/tests/* --error-exitcode=1
  - cd "${TRAVIS_BUILD_DIR}"

after_success:
  - bash <(curl -s https://codecov.io/bash)